### ISSUE TITLE
Fails with perls < 5.22

### ISSUE THREAD

**Issue by andk** [reyjrar/WWW-Subsonic#3]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/94194150

If you want to keep the <<>> Syntax, could you please declare the requirement? That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Thanks,

**Comment by reyjrar** [comment]
Fixed in 0.006
